### ISSUE TITLE
Alway throw error while uploading video

### ISSUE THREAD

**Issue by meghjoshi** [majorleaguesoccer/ooyala#3]
bellow is my code and i am using https://www.npmjs.com/package/ooyala this NPM module

router.get('/uploadvideo', function(req, res, next) {

    fs.readFile(__dirname +'/../public/video/music_2016_stl.mp4', 'utf8', function(err, buffer) {
    console.log(err)
        // Setup our new video asset. This example can be used as an `update/replacement`
        // for existing videos if an `embed_code` property is added.
        var myVideo = {
            name: 'awesome thing i did'
            , description: 'mom get the camera!!'
            , file_name: 'my_asset.mp4' // Ooyala tracks these names as unique keys
            , file_size: buffer.length // Ooyala needs this to generate upload URLs
            , labels: [
                '/Summer 2016'
                , '/Foods'
            ]
        };

        api
        // Create or update the asset, set the metadata, then sync the given labels.
            .syncVideoAsset(myVideo)

            // Here you can check any kind of video status, or save the remote data before
            // continuing. It is recommended to capture state here in case of upload failure.
            .then(function(remoteVideo) {
                console.log(remoteVideo);
                console.log('here');
                // Check if something else is uploading it, we could also check for `duplicate`
                // or `error` status, as Ooyala will respond with an error if attempted.
                if (remoteVideo.status === 'uploading') {
                    return Promise.reject(new Error('ooyala will error if we try'))
                }
               // else {
                    var videoId = remoteVideo.embed_code;
                    console.log(videoId)
                    return api.uploadFullVideoAsset(videoId, buffer)

               // }
                // The `embed_code` property is the primary video ID

                // Allow the SDK to handle the multi-step upload workflow, with retry logic
                //return api.uploadFullVideoAsset(videoId, buffer)
            })

            .then(function(err,ress) {
                console.log(err);
                console.log(ress);
                //res.json(ress);
            })

            // Error handling
            .catch(Ooyala.ProcessingVideoError, function(err) {
                console.log(err);
                // The video is still transcoding, check for updates from Ooyala before trying again
            })
            .catch(Ooyala.DuplicateVideoError, function(err) {
                console.log(err);

                // The video `file_name` used is in use by another video asset
            })
            .catch(Ooyala.Error, function(err) {
                console.log(err);

                // Something else went wrong within the Ooyala API or this SDK
            })
            .catch(function(err) {
                console.log(err);

                // Default error catcher, should always be used with Promises
            })
    })

});

**Comment by sorensen** [comment]
@meghjoshi Can you provide more information here? What is the error being thrown?

**Comment by meghjoshi** [comment]
Here is the link of  image that shows you error
![error ooyala](https://cloud.githubusercontent.com/assets/20103619/17926760/185774c8-6a10-11e6-8224-97d49fb347bb.png)

http://i.prntscr.com/359056766b85490bb99d420b04864a70.png

**Comment by meghjoshi** [comment]
and if i comment out that part from upload.js file and try to run then i'm getting missing chunks error every time

**Comment by sorensen** [comment]
This issue is because you are reading the `.mp4` file as `utf8` encoding, which returns a `String` in node.js. You will need to use a literal `Buffer` instance to upload to ooyala.

**Comment by meghjoshi** [comment]
check below screen shot 
http://i.prntscr.com/13b7d5eeb0104bff8eda843ad31ce56f.png
this fs.readFile convert video file to string buffer so i think i am right there is some other issues.

**Comment by sorensen** [comment]
@meghjoshi Please take a look at the documentation for node fs. You are returning a `String` because you are specifying the `utf8` encoding. Remove the `utf8` argument.

`fs.readFile('file.mp4', function(err, buffer){})`

https://nodejs.org/api/fs.html#fs_fs_readfile_file_options_callback

**Comment by sorensen** [comment]
@meghjoshi My apologies on this one, the example in the documentation is incorrect. I will update to avoid confusion, sorry about that.
